[package]
name = "tpc9000/typeguard"
version = "6.0.0-alpha.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["tpc9000"]

[dependencies]
TableUtil = "tpc9000/tableutil@0.8.1"